In [2]:
import numpy as np 
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix

from LSSVMMultiClass import LSSVMMultiClass

In [3]:
# iris laden
iris = load_iris()

X = iris.data
y = iris.target 

print(np.unique(y))

[0 1 2]


In [4]:
# Train/test split 
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [5]:
# model maken 
model = LSSVMMultiClass(
    gamma=1.0,
    kernel="rbf",
    sigma=1.0,
)

#trainen 
model.fit(X_train, y_train)

print(model.classes)
print(model.models)

(120,)
(120,)
(120,)
[0 1 2]
{np.int64(0): LSSVMClassification(kernel='rbf'), np.int64(1): LSSVMClassification(kernel='rbf'), np.int64(2): LSSVMClassification(kernel='rbf')}


In [6]:
# testen
pred = model.predict(X_test)

print(pred)
print(np.unique(pred))


[0 2 1 1 0 1 0 0 2 1 2 2 2 1 0 0 0 1 1 2 0 2 1 2 2 2 1 0 2 0]
[0 1 2]


In [7]:
# accuraatheid 
acc = accuracy_score(y_test, pred)
cm = confusion_matrix(y_test, pred)

print("Accuracy:", acc)
print(cm)

# vergelijken met sklearn
from sklearn.svm import SVC

svc = SVC(
    kernel="rbf",
    gamma=1.0,
    C=1.0
)

svc.fit(X_train, y_train)

pred_svc = svc.predict(X_test)

print("LS-SVM :", accuracy_score(y_test, pred))
print("SVC    :", accuracy_score(y_test, pred_svc))

Accuracy: 0.9666666666666667
[[10  0  0]
 [ 0  9  1]
 [ 0  0 10]]
LS-SVM : 0.9666666666666667
SVC    : 0.9666666666666667
